config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get 'about', to: "pages#about"
  get 'signup', to: "users#new"
  resources :users, except: [:new]
  resources :articles
  get 'login', to: "sessions#new"
  post 'login', to: "sessions#create"
  delete 'logout', to: "sessions#destroy"

  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :user
	has_many :article_categories
  has_many :categories, through: :article_categories


	validates :title, presence: true, length: {minimum:6, maximum:100}
	validates :description, presence: true, length: {minimum:10, maximum:300}
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories

  validates :name, presence: true, uniqueness: { case_sensitive: false }, length: {minimum:5, maximum:20}
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }

  has_many :articles, dependent: :destroy

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	validates :username, presence: true, length: { minimum:3, maximum:25 }, uniqueness: { case_sensitive: false }
	validates :email, presence: true, length: { maximum:105 }, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def required_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :set_article, only:[:show, :edit, :update, :destroy]
	before_action :required_user, except:[:index, :show]
	before_action :required_same_user, only:[:edit, :update, :destroy]

	def index
		@articles = Article.paginate(page: params[:page], per_page: 4)
	end

	def show
	end

	def new
		@article = Article.new
	end

	def edit
	end

	def create
		@article = Article.new(article_params)
		@article.user = current_user
		if @article.save
			flash[:notice] = "Article saved!"
			redirect_to @article
		else
			render 'new'
		end
	end

	def update
		if @article.update(article_params)
			flash[:notice] = "Article updated!"
			redirect_to @article
		else
			render 'edit'
		end
	end

	def destroy
		@article.destroy
		redirect_to articles_path
	end

	private

	def set_article
		@article = Article.find(params[:id])
	end

	def article_params
		params.require(:article).permit(:title, :description, category_ids: [])
	end

	def required_same_user
		if current_user != @article.user && !current_user.admin?
			flash[:alert] = "This is not your article"
      redirect_to root_path
		end
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]

  def index
    @categories = Category.paginate(page: params[:page], per_page: 4)
  end

  def show
    @category = Category.find(params[:id])
    @articles = @category.articles.paginate(page: params[:page], per_page: 4)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = 'Category created!'
      redirect_to @category
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
			flash[:notice] = "User info updated!"
			redirect_to user_path(@category)
		else
			render 'edit'
		end
  end

  private
  
  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = "Only admins can perform that action"
      redirect_to categories_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
		redirect_to articles_path if logged_in?
	end

	def about
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:sessions][:email].downcase)
    if user && user.authenticate(params[:sessions][:password])
      session[:user_id] = user.id
      flash[:notice] = "Succesfully loged in!"
      redirect_to user
    else
      flash.now[:alert] = "Wrong credentials"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Succesfully loged out!"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only:[:edit, :update, :show, :destroy]
	before_action :required_same_user, only:[:edit, :update, :destroy]

  def index
		@users = User.paginate(page: params[:page], per_page: 4)
  end

  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 4)
  end

  def new
    @user = User.new
	end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome #{@user.username}!"
			redirect_to articles_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
		if @user.update(user_params)
			flash[:notice] = "User info updated!"
			redirect_to user_path(@user)
		else
			render 'edit'
		end
	end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "Account and articles associated succesfully deleted"
		redirect_to root_path
  end


  private

  def user_params
		params.require(:user).permit(:username, :email, :password)
	end

  def set_user
		@user = User.find(params[:id])
  end

	def required_same_user
		if current_user != @user && !current_user.admin?
			flash[:alert] = "Access forbidden"
      redirect_to root_path
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = { size: 80 })
    # get the email from URL-parameters or what have you and make lowercase
    email_address = user.email.downcase
    
    # create the md5 hash
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    # compile URL which can be used in <img src="RIGHT_HERE"...
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"

    image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div class="container">
	<% @articles.each do |article|  %>
		<div class="row justify-content-md-center">
			<div class="col-8 mt-4" style="margin: 0 auto;">
				<div class="card text-center shadow mb-5 bg-white rounded">
					<div class="card-header">
						By <%= link_to article.user.username, user_path(article.user) %> <br>
						<% if article.categories.any? %>
							<% article.categories.each do |category| %>
								<div class="badge"><%= link_to category.name, category_path(category) %></div>
							<% end %>
						<% end %>
					</div>
					<div class="card-body">
						<h5 class="card-title"><%= link_to article.title, article_path(article), class:"text-success" %></h5>
						<p class="card-text"><%= truncate(article.description, length: 100) %></p>
						
						<%= link_to "View", article_path(article), class:"btn btn-outline-success"  %>
						<% if logged_in? && (current_user == article.user || current_user.admin?) %>
							<%= link_to "Edit", edit_article_path(article), class:"btn btn-outline-info"  %>
							<%= link_to "Delete", article_path(article), class:"btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"}  %>
						<% end %>
					</div>
					<div class="card-footer text-muted">
						<small> Created <%= time_ago_in_words(article.created_at) %> ago,
						edited <%= time_ago_in_words(article.updated_at) %> ago
						</small>
					</div>
				</div>
			</div>
		</div>
	<% end %>
</div>

app/views/articles/_form.html.erb
<div class="container">
	<div class="row justify-content-center">
		<div class="col-10">
			<%= render 'shared/errors', obj: @article %>
				<%= form_with(model: @article, class:"shadow p-3 mb-3 bg-info rounded", local: true)  do |f| %>
					<div class="form-group row mb-2">
						<%= f.label :title, class:"col-2 col-form-label text-light" %>
						<div class="col-10">
							<%= f.text_field :title, class:"form-control shadow rounded", placeholder:"Title" %>
						</div>
					</div>
					<div class="form-group row">
						<%= f.label :description, class:"col-2 col-form-label text-light" %>
						<div class="col-10">
							<%= f.text_area :description, rows:10, class:"form-control shadow rounded", placeholder:"Description" %>
						</div>
					</div>

					<div class="form-group row">
						<%= f.label :category, class:"col-2 col-form-label text-light" %>
						<div class="col-10">
							<%= f.collection_select(:category_ids, Category.all, :id, :name, {prompt: "make your selection (It can be empty)"}, {multiple: true, size: 3, class: "custom-select shadow rounded"}) %>
						</div>
					</div>


					<div class="form-group row justify-content-center mt-4">
						<div class="col-4">
							<%= f.submit class:"btn btn-outline-light btn-lg" %>
						</div>
					</div>
				<% end %>		
			<div class="mb-3 d-flex justify-content-center">
				<%= link_to "[ Back to index ]", articles_path, class:"text-info" %>
			</div>
		</div>
	</div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Edit article</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Our articles</h1>


<div class="apple_pagination">
	<%= will_paginate @articles, :container => false %>
</div>

<%= render 'article' %>

<div class="mb-3 d-flex justify-content-center">
	<%= link_to '[ Create new article ]', new_article_path, class:"text-info" %>
</div>

<div class="apple_pagination">
	<%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
<h1 class="text-center mt-4">Create a new article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<h1 class="text-center mt-4"><%= @article.title %></h1>
<div class="container">
	<div class="row justify-content-md-center">
		<div class="col-8 mt-4">
			<div class="card text-center shadow mb-5 bg-white rounded">
				<div class="card-header">
					By <%= @article.user.username %>
					<%= link_to gravatar_for(@article.user), user_path(@article.user) %>
					<% if @article.categories.any? %>
						<% @article.categories.each do |category| %>
							<div class="badge"><%= link_to category.name, category_path(category) %></div>
						<% end %>
					<% end %>
				</div>
				<div class="card-body">
					<div class="card-text"><%= simple_format(@article.description) %></div>
					<% if logged_in? && (current_user == @article.user || current_user.admin?) %>
						<%= link_to "Edit", edit_article_path(@article), class:"btn btn-outline-info"  %>
						<%= link_to "Delete", article_path(@article), class:"btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"}  %>
					<% end %>
				</div>
				<div class="card-footer text-muted">
					<small> Created <%= time_ago_in_words(@article.created_at) %> ago,
					edited <%= time_ago_in_words(@article.updated_at) %> ago
					</small>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="mb-3 d-flex justify-content-center">
	<%= link_to '[ Back to index ]', articles_path, class:"text-info" %>
</div>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>
<%= form_with(model: @category, class:"shadow p-3 mb-3 bg-info rounded", local: true)  do |f| %>
  <div class="form-group row mb-2">
    <%= f.label :name, "Category name", class:"col-2 col-form-label text-light" %>
    <div class="col-10">
      <%= f.text_field :name, class:"form-control shadow rounded", placeholder:"Enter a category name" %>
    </div>
  </div>


  <div class="form-group row justify-content-center mt-4">
    <div class="col-4">
      <%= f.submit class:"btn btn-outline-light btn-lg" %>
    </div>
  </div>
<% end %>	

app/views/categories/edit.html.erb
<h1 class="text-center mt-4">Edit category</h1>

<div class="container">
	<div class="row justify-content-center">
		<div class="col-10">
			<%= render 'form' %>

			<div class="mb-3 d-flex justify-content-center">
				<%= link_to "[ Back to index ]", categories_path, class:"text-info" %>
			</div>
		</div>
	</div>
</div>

app/views/categories/index.html.erb
<h1 class="text-center mt-4">Our categories</h1>

<div class="apple_pagination">
	<%= will_paginate @categories, :container => false %>
</div>

<div class="container">
	<% @categories.each do |category|  %>
		<div class="row justify-content-md-center">
			<div class="col-4 mt-4" style="margin: 0 auto;">
				<div class="card text-center shadow mb-5 bg-white rounded">
					<div class="card-body">
						<h5 class="card-title"><%= link_to category.name, category_path(category), class:"text-success" %></h5>
						<p class="card-text"><%= pluralize(category.articles.count, "article") %> </p>
					</div>
					<div class="card-footer text-muted">
						<small> Created <%= time_ago_in_words(category.created_at) %> ago,
						edited <%= time_ago_in_words(category.updated_at) %> ago
						</small>
					</div>
				</div>
			</div>
		</div>
	<% end %>
</div>

<div class="apple_pagination">
	<%= will_paginate @categories, :container => false %>
</div>

app/views/categories/new.html.erb
<h1 class="text-center mt-4">Create a new article</h1>

<div class="container">
	<div class="row justify-content-center">
		<div class="col-10">
			<%= render 'shared/errors', obj: @category %>
				<%= form_with(model: @category, class:"shadow p-3 mb-3 bg-info rounded", local: true)  do |f| %>
					<div class="form-group row mb-2">
						<%= f.label :name, "Category name", class:"col-2 col-form-label text-light" %>
						<div class="col-10">
							<%= f.text_field :name, class:"form-control shadow rounded", placeholder:"Enter a category name" %>
						</div>
					</div>


					<div class="form-group row justify-content-center mt-4">
						<div class="col-4">
							<%= f.submit class:"btn btn-outline-light btn-lg" %>
						</div>
					</div>
				<% end %>	

			<div class="mb-3 d-flex justify-content-center">
				<%= link_to "[ Back to index ]", articles_path, class:"text-info" %>
			</div>
		</div>
	</div>
</div>

app/views/categories/show.html.erb
<h1 class="text-center mt-4">Category: <%= @category.name %></h1>

<% if logged_in? && current_user.admin? %>
	<div class="text-center mt-4">
		<%= link_to "Edit category name", edit_category_path(@category), class:"btn btn-outline-info" %>
	</div>
<% end %>

<h3 class="text-center mt-4">Articles</h3>

<div class="apple_pagination">
	<%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles/article' %>

<div class="apple_pagination">
	<%= will_paginate @articles, :container => false %>
</div>

<div class="mb-3 d-flex justify-content-center">
	<%= link_to '[ Back to categories index ]', categories_path, class:"text-info" %>
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="flex-shrink-0 py-4 bg-dark text-white">
	<div class="container text-center">
		<small>Copyright &copy; <%= link_to "My Projects", "http://tomagprojects.herokuapp.com/", target: "_blank", class:"text-white," %></small>
	</div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
	<% flash.each do |key, msg| %>
		<div class="alert alert-<%= key == "notice" ? "success" : "danger" %>" role="alert">
			<%= msg %>
		</div>
	<% end %>
</div>

app/views/layouts/_navbar.html.erb
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
				<%= link_to "ALPHA BLOG", root_path, class: "navbar-brand", id: "logo" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <%= link_to "Users", users_path, class: "nav-link" %>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Articles
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><%= link_to "Index", articles_path, class:"dropdown-item" %></li>               
                  <% if logged_in? %>
                    <li><hr class="dropdown-divider"></li>
                    <li><%= link_to "Create new", new_article_path, class:"dropdown-item" %></li>
                  <% end %>
              </ul>
            </li>

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Categories
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><%= link_to "View categories", categories_path, class:"dropdown-item" %></li>
                <% if logged_in? && current_user.admin? %>
                  <li><%= link_to "Create new category", new_category_path, class:"dropdown-item" %></li>
                <% end %>
              </ul>
            </li>
            
            <% if logged_in? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <%= "(Admin)" if current_user.admin? %> <%= current_user.username %>
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><%= link_to "My profile", user_path(current_user), class:"dropdown-item" %></li>
                <li><%= link_to "Edit my profile", edit_user_path(current_user), class:"dropdown-item" %></li>
                <li><%= link_to "Logout", logout_path, class:"dropdown-item", method: :delete %></li>
              </ul>
            </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "Log in", login_path, class:"nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Sign up", signup_path, class:"nav-link" %>
              </li>
            <% end %>
          </ul>
          <form class="d-flex">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'styles', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">

    <%= render 'layouts/navbar' %>
    
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is the about page!</h1>

<%= link_to 'home', root_path %>
<%= link_to "Articles index", articles_path %>

app/views/pages/home.html.erb
<div class="container" id="home-container">
	<div class="jumbotron text-center text-white">
		<div class="text">
			<h1 class="display-4">Alpha blog!</h1>
			<p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
			<hr class="my-4">
			<p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
			<p class="lead">
				<%= link_to "Sign up", signup_path, class:"btn btn-success btn-lg" %>
			</p>
		</div>
	</div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
	<div class="alert alert-danger" role="alert">
			<h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved:</h4>
			<ul>
				<% obj.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
	</div>
<% end %>	

app/views/users/_form.html.erb
<div class="container">
	<div class="row justify-content-center">
		<div class="col-10">
			<%= render 'shared/errors', obj: @user %>
				<%= form_with(model: @user, class:"shadow p-3 mb-3 bg-info rounded", local: true)  do |f| %>
					<div class="form-group row mb-2">
						<%= f.label :username, class:"col-2 col-form-label text-light" %>
						<div class="col-10">
							<%= f.text_field :username, class:"form-control shadow rounded", placeholder:"Enter a username" %>
						</div>
					</div>

					<div class="form-group row mb-2">
						<%= f.label :email, class:"col-2 col-form-label text-light" %>
						<div class="col-10">
							<%= f.email_field :email, class:"form-control shadow rounded", placeholder:"Enter your email" %>
						</div>
					</div>


					<div class="form-group row">
						<%= f.label :password, class:"col-2 col-form-label text-light" %>
						<div class="col-10">
							<%= f.password_field :password, class:"form-control shadow rounded", placeholder:"Enter your password" %>
						</div>
					</div>

					<div class="form-group row justify-content-center mt-4">
						<div class="col-4">
							<%= f.submit(@user.new_record? ? "Sign up" : "Update", class:"btn btn-outline-light btn-lg") %>
						</div>
					</div>
				<% end %>		
			<div class="mb-3 d-flex justify-content-center">
				<%= link_to "[ Back to index ]", articles_path, class:"text-info" %>
			</div>
		</div>
	</div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit user info</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-4">Alpha blog users</h1>

<div class="container">
	<div class="apple_pagination">
		<%= will_paginate @users, :container => false %>
	</div>

	<% @users.each do |user|  %>
		<div class="row justify-content-md-center">
			<div class="col-8 mt-4">
				<div class="card text-center shadow mb-5 bg-white rounded">
					<div class="card-header">
						<%= link_to user.username, user_path(user) %>
						
					</div>
					<div class="card-body">
						<%= link_to gravatar_for(user, size: 200), user_path(user)  %>
						<p class="card-text"><%= pluralize(user.articles.count, "article") %> </p>
						<%= link_to "View profile", user_path(user), class:"btn btn-outline-success"  %>
						<% if logged_in? && (current_user == user || current_user.admin?) %>
							<%= link_to "Edit profile", edit_user_path(user), class:"btn btn-outline-info"  %>
							<%= link_to "Remove profile", user_path(user), class:"btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"}  %>
						<% end %>
					</div>
					<div class="card-footer text-muted">
						<small> Joined <%= time_ago_in_words(user.created_at) %> ago
						</small>
					</div>
				</div>
			</div>
		</div>
	<% end %>
	
	<div class="apple_pagination">
		<%= will_paginate @users, :container => false %>
	</div>	


</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Sign up for Alpha blog</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<% if current_user == @user %>
	<h1 class="text-center mt-4">Welcome <%= @user.username %></h1>
<% else %>
	<h1 class="text-center mt-4"><%= @user.username %>'s page</h1>
<% end %>

<%= gravatar_for @user, size: 200 %>


<% if logged_in? && current_user == @user %>
	<div class="text-center mt-4">
		<%= link_to "Edit your profile", edit_user_path(@user), class:"btn btn-outline-info" %>
	</div>
	<div class="text-center mt-4">
		<%= link_to "Remove your profile", user_path(@user), class:"btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"}  %>
<% end %>


<% if logged_in? && current_user == @user && @user.articles.count > 0 %>
	<h3 class="text-center mt-4">Your articles</h3>
<% elsif logged_in? && current_user == @user %>
	<h3 class="text-center mt-4">You haven't written any articles yet. Do you want to write <%= link_to "one", new_article_path %>?</h3>
<% elsif @user.articles.count > 0 %>
	<h3 class="text-center mt-4"><%= @user.username %>'s articles</h3>
<% else %>
	<h3 class="text-center mt-4">This user has not yet written any article</h3>
<% end %>


<div class="apple_pagination">
	<%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles/article' %>

<div class="apple_pagination">
	<%= will_paginate @articles, :container => false %>
</div>

<div class="mb-3 d-flex justify-content-center">
	<%= link_to '[ Back to user index ]', users_path, class:"text-info" %>
</div>